import net.ooder.annotation.IconEnumstype;

// ... existing code ...
public enum AppendType implements IconEnumstype {
    append("内部渲染", "fas fa-box"), ref("引用MODULE", "fas fa-cubes"), runtime("运行期", "fas fa-clock");
//// ... existing code ...