package net.ooder.esd.annotation.ui;


import net.ooder.annotation.IconEnumstype;

// 保留前三个已经正确升级的图标
public enum CustomImageType implements IconEnumstype {
    o("fa-solid fa-lg fa-calendar-plus", "fa-solid fa-lg fa-calendar-plus"),
    close("fa-solid fa-lg fa-times", "fa-solid fa-lg fa-times"),
    notch("fa-solid fa-lg fa-circle-notch", "fa-solid fa-lg fa-circle-notch"),
    
    // spafont 图标升级
    data("fa-solid fa-database", "fa-solid fa-database"),
    debug("fa-solid fa-bug", "fa-solid fa-bug"),
    debug1("fa-solid fa-vial", "fa-solid fa-vial"),
    video("fa-solid fa-video", "fa-solid fa-video"),
    webapi("fa-solid fa-server", "fa-solid fa-server"),
    cut("fa-solid fa-cut", "fa-solid fa-cut"),
    delete("fa-solid fa-trash-alt", "fa-solid fa-trash-alt"),
    designview("fa-solid fa-paint-brush", "fa-solid fa-paint-brush"),
    icondomnode("fa-solid fa-code-branch", "fa-solid fa-code-branch"),
    deletepath("fa-solid fa-unlink", "fa-solid fa-unlink"),
    edit("fa-solid fa-edit", "fa-solid fa-edit"),
    deletefile("fa-solid fa-file-excel", "fa-solid fa-file-excel"),
    event("fa-solid fa-bolt", "fa-solid fa-bolt"),
    editpath("fa-solid fa-link", "fa-solid fa-link"),
    empty("fa-solid fa-archive", "fa-solid fa-archive"),
    file("fa-solid fa-file", "fa-solid fa-file"),
    explore("fa-solid fa-search", "fa-solid fa-search"),
    fillcell("fa-solid fa-fill", "fa-solid fa-fill"),
    filexml("fa-solid fa-file-code", "fa-solid fa-file-code"),
    formatjs("fa-solid fa-file-js", "fa-solid fa-file-js"),
    formatjson("fa-solid fa-file-export", "fa-solid fa-file-export"),
    frame("fa-solid fa-border-all", "fa-solid fa-border-all"),
    hmirror("fa-solid fa-arrows-h", "fa-solid fa-arrows-h"),
    hash("fa-solid fa-hashtag", "fa-solid fa-hashtag"),
    function("fa-solid fa-cogs", "fa-solid fa-cogs"),
    gallery("fa-solid fa-images", "fa-solid fa-images"),
    html("fa-solid fa-code", "fa-solid fa-code"),
    arrowtop("fa-solid fa-arrow-up", "fa-solid fa-arrow-up"),
    bigup("fa-solid fa-arrow-circle-up", "fa-solid fa-arrow-circle-up"),
    indent("fa-solid fa-indent", "fa-solid fa-indent"),
    js("fab fa-js", "fab fa-js"),
    jumpto("fa-solid fa-jump-forward", "fa-solid fa-jump-forward"),
    language("fa-solid fa-language", "fa-solid fa-language"),
    sfile("fa-solid fa-file-code", "fa-solid fa-file-code"),
    manual("fa-solid fa-book", "fa-solid fa-book"),
    links("fa-solid fa-link", "fa-solid fa-link"),
    login("fa-solid fa-sign-in-alt", "fa-solid fa-sign-in-alt"),
    movebackward("fa-solid fa-backward", "fa-solid fa-backward"),
    module("fa-solid fa-cube", "fa-solid fa-cube"),
    down("fa-solid fa-chevron-down", "fa-solid fa-chevron-down"),
    moveforward("fa-solid fa-forward", "fa-solid fa-forward"),
    up("fa-solid fa-chevron-up", "fa-solid fa-chevron-up"),
    newfile("fa-solid fa-file-export", "fa-solid fa-file-export"),
    newprj("fa-solid fa-project-diagram", "fa-solid fa-project-diagram"),
    ok("fa-solid fa-check", "fa-solid fa-check"),
    openprj("fa-solid fa-folder-open", "fa-solid fa-folder-open"),
    iconpackage("fa-solid fa-box", "fa-solid fa-box"),
    options("fa-solid fa-cog", "fa-solid fa-cog"),
    page("fa-solid fa-file-alt", "fa-solid fa-file-alt"),
    phonegap("fa-solid fa-mobile-alt", "fa-solid fa-mobile-alt"),
    paste("fa-solid fa-paste", "fa-solid fa-paste"),
    pic("fa-solid fa-image", "fa-solid fa-image"),
    previewpage("fa-solid fa-eye", "fa-solid fa-eye"),
    preview("fa-solid fa-eye", "fa-solid fa-eye"),
    property("fa-solid fa-sliders-h", "fa-solid fa-sliders-h"),
    rename("fa-solid fa-edit", "fa-solid fa-edit"),
    project("fa-solid fa-project-diagram", "fa-solid fa-project-diagram"),
    rendermode("fa-solid fa-palette", "fa-solid fa-palette"),
    resetpath("fa-solid fa-sync-alt", "fa-solid fa-sync-alt"),
    rotateleft("fa-solid fa-undo", "fa-solid fa-undo"),
    rotateright("fa-solid fa-redo", "fa-solid fa-redo"),
    rpc("fa-solid fa-network-wired", "fa-solid fa-network-wired"),
    save("fa-solid fa-save", "fa-solid fa-save"),
    saveall("fa-solid fa-save", "fa-solid fa-save"),
    searchreplace("fa-solid fa-search", "fa-solid fa-search"),
    select("fa-solid fa-check-square", "fa-solid fa-check-square"),
    select1("fa-solid fa-check-square", "fa-solid fa-check-square"),
    setup("fa-solid fa-cog", "fa-solid fa-cog"),
    shouhou("fa-solid fa-headset", "fa-solid fa-headset"),
    star("fa-solid fa-star", "fa-solid fa-star"),
    settingprj("fa-solid fa-cog", "fa-solid fa-cog"),
    theme("fa-solid fa-palette", "fa-solid fa-palette"),
    tool("fa-solid fa-toolbox", "fa-solid fa-toolbox"),
    unkown("fa-solid fa-question", "fa-solid fa-question"),
    tools("fa-solid fa-tools", "fa-solid fa-tools"),
    values("fa-solid fa-list-ol", "fa-solid fa-list-ol"),
    ivideo("fa-solid fa-video", "fa-solid fa-video"),
    var("fa-solid fa-code", "fa-solid fa-code"),
    vmirror("fa-solid fa-arrows-v", "fa-solid fa-arrows-v"),
    shukongjian("fa-solid fa-cubes", "fa-solid fa-cubes"),
    viewpoint("fa-solid fa-eye", "fa-solid fa-eye"),
    action("fa-solid fa-play", "fa-solid fa-play"),
    x("fa-solid fa-times", "fa-solid fa-times"),
    wbdiconsoftswf("fab fa-adobe", "fab fa-adobe"),
    action1("fa-solid fa-play-circle", "fa-solid fa-play-circle"),
    addpath("fa-solid fa-plus-square", "fa-solid fa-plus-square"),
    alignh("fa-solid fa-align-center", "fa-solid fa-align-center"),
    alignl("fa-solid fa-align-left", "fa-solid fa-align-left"),
    alignc("fa-solid fa-align-center", "fa-solid fa-align-center"),
    alignm("fa-solid fa-align-justify", "fa-solid fa-align-justify"),
    aligncell("fa-solid fa-table", "fa-solid fa-table"),
    alignt("fa-solid fa-align-top", "fa-solid fa-align-top"),
    alignwh("fa-solid fa-expand-arrows-alt", "fa-solid fa-expand-arrows-alt"),
    alingb("fa-solid fa-align-bottom", "fa-solid fa-align-bottom"),
    alignw("fa-solid fa-expand-alt", "fa-solid fa-expand-alt"),
    array("fa-solid fa-list", "fa-solid fa-list"),
    app("fa-solid fa-mobile-alt", "fa-solid fa-mobile-alt"),
    arrow("fa-solid fa-arrow-right", "fa-solid fa-arrow-right"),
    audio("fa-solid fa-volume-up", "fa-solid fa-volume-up"),
    breakpath("fa-solid fa-unlink", "fa-solid fa-unlink"),
    astext("fa-solid fa-font", "fa-solid fa-font"),
    cancel("fa-solid fa-times", "fa-solid fa-times"),
    saudio("fa-solid fa-volume-up", "fa-solid fa-volume-up"),
    buttonviews("fa-solid fa-th", "fa-solid fa-th"),
    button("fa-solid fa-square", "fa-solid fa-square"),
    block("fa-solid fa-cube", "fa-solid fa-cube"),
    buttonview("fa-solid fa-th-large", "fa-solid fa-th-large"),
    checkbox("fa-solid fa-check-square", "fa-solid fa-check-square"),
    iconslist("fa-solid fa-list", "fa-solid fa-list"),
    hiddeninput("fa-solid fa-key", "fa-solid fa-key"),
    imagebutton("fa-solid fa-image", "fa-solid fa-image"),
    image("fa-solid fa-image", "fa-solid fa-image"),
    label("fa-solid fa-font", "fa-solid fa-font"),
    layout("fa-solid fa-th", "fa-solid fa-th"),
    input("fa-solid fa-keyboard", "fa-solid fa-keyboard"),
    clear("fa-solid fa-times-circle", "fa-solid fa-times-circle"),
    iconclass("fa-solid fa-code", "fa-solid fa-code"),
    click("fa-solid fa-mouse-pointer", "fa-solid fa-mouse-pointer"),
    list("fa-solid fa-list", "fa-solid fa-list"),
    closepath("fa-solid fa-times-circle", "fa-solid fa-times-circle"),
    clone("fa-solid fa-clone", "fa-solid fa-clone"),
    menu("fa-solid fa-bars", "fa-solid fa-bars"),
    menubar("fa-solid fa-ellipsis-h", "fa-solid fa-ellipsis-h"),
    nativebutton("fa-solid fa-square", "fa-solid fa-square"),
    codeview("fa-solid fa-code", "fa-solid fa-code"),
    code("fa-solid fa-code", "fa-solid fa-code"),
    numberinput("fa-solid fa-hashtag", "fa-solid fa-hashtag"),
    coin("fa-solid fa-coins", "fa-solid fa-coins"),
    com("fa-solid fa-plug", "fa-solid fa-plug"),
    conf("fa-solid fa-cog", "fa-solid fa-cog"),
    conf1("fa-solid fa-cogs", "fa-solid fa-cogs"),
    coms("fa-solid fa-plug", "fa-solid fa-plug"),
    console("fa-solid fa-terminal", "fa-solid fa-terminal"),
    config("fa-solid fa-cog", "fa-solid fa-cog"),
    pager("fa-solid fa-sync-alt", "fa-solid fa-sync-alt"),
    panel("fa-solid fa-layer-group", "fa-solid fa-layer-group"),
    copy("fa-solid fa-copy", "fa-solid fa-copy"),
    progressbar("fa-solid fa-tasks", "fa-solid fa-tasks"),
    richeditor("fa-solid fa-edit", "fa-solid fa-edit"),
    radiobox("fa-solid fa-dot-circle", "fa-solid fa-dot-circle"),
    slider("fa-solid fa-sliders-h", "fa-solid fa-sliders-h"),
    password("fa-solid fa-lock", "fa-solid fa-lock"),
    span("fa-solid fa-font", "fa-solid fa-font"),
    stacks("fa-solid fa-layer-group", "fa-solid fa-layer-group"),
    css("fab fa-css3-alt", "fab fa-css3-alt"),
    statusbtns("fa-solid fa-tasks", "fa-solid fa-tasks"),
    spinner("fa-solid fa-spinner", "fa-solid fa-spinner"),
    tabs("fa-solid fa-table", "fa-solid fa-table"),
    statusbutton("fa-solid fa-toggle-on", "fa-solid fa-toggle-on"),
    textarea("fa-solid fa-align-left", "fa-solid fa-align-left"),
    timeinput("fa-solid fa-clock", "fa-solid fa-clock"),
    toolbar("fa-solid fa-toolbar", "fa-solid fa-toolbar"),
    timer("fa-solid fa-stopwatch", "fa-solid fa-stopwatch"),
    treebar("fa-solid fa-sitemap", "fa-solid fa-sitemap"),
    treeview("fa-solid fa-tree", "fa-solid fa-tree"),
    url("fa-solid fa-link", "fa-solid fa-link"),
    custom("fa-solid fa-wrench", "fa-solid fa-wrench"),
    com2("fa-solid fa-plug", "fa-solid fa-plug"),
    com3("fa-solid fa-plug", "fa-solid fa-plug"),
    mqtt("fa-solid fa-network-wired", "fa-solid fa-network-wired"),
    
    // ood 图标升级
    ood("fa-solid fa-cube", "fa-solid fa-cube"),
    placeholder("fa-solid fa-map-marker-alt", "fa-solid fa-map-marker-alt"),
    iempty("fa-solid fa-box-open", "fa-solid fa-box-open"),
    loading("fa-solid fa-spinner", "fa-solid fa-spinner"),
    istar("fa-solid fa-star", "fa-solid fa-star"),
    smill("fa-solid fa-smile", "fa-solid fa-smile"),
    trash("fa-solid fa-trash", "fa-solid fa-trash"),
    error("fa-solid fa-exclamation-triangle", "fa-solid fa-exclamation-triangle"),
    back("fa-solid fa-arrow-left", "fa-solid fa-arrow-left"),
    bold("fa-solid fa-bold", "fa-solid fa-bold"),
    bgcolor("fa-solid fa-fill", "fa-solid fa-fill"),
    breaklink("fa-solid fa-unlink", "fa-solid fa-unlink"),
    clock("fa-solid fa-clock", "fa-solid fa-clock"),
    circle("fa-solid fa-circle", "fa-solid fa-circle"),
    ibigup("fa-solid fa-arrow-up", "fa-solid fa-arrow-up"),
    icode("fa-solid fa-code", "fa-solid fa-code"),
    idialog("fa-solid fa-window-maximize", "fa-solid fa-window-maximize"),
    bullet("fa-solid fa-circle", "fa-solid fa-circle"),
    date("fa-solid fa-calendar", "fa-solid fa-calendar"),
    dragadd("fa-solid fa-plus", "fa-solid fa-plus"),
    dragmove("fa-solid fa-arrows-alt", "fa-solid fa-arrows-alt"),
    dragcopy("fa-solid fa-copy", "fa-solid fa-copy"),
    dropdown("fa-solid fa-chevron-down", "fa-solid fa-chevron-down"),
    dragstop("fa-solid fa-stop", "fa-solid fa-stop"),
    ifile("fa-solid fa-file", "fa-solid fa-file"),
    expand("fa-solid fa-chevron-down", "fa-solid fa-chevron-down"),
    fold("fa-solid fa-chevron-right", "fa-solid fa-chevron-right"),
    filter("fa-solid fa-filter", "fa-solid fa-filter"),
    font("fa-solid fa-font", "fa-solid fa-font"),
    forecolor("fa-solid fa-palette", "fa-solid fa-palette"),
    formatbrush("fa-solid fa-paint-brush", "fa-solid fa-paint-brush"),
    formatclear("fa-solid fa-eraser", "fa-solid fa-eraser"),
    iindent("fa-solid fa-indent", "fa-solid fa-indent"),
    ihtml("fa-solid fa-code", "fa-solid fa-code"),
    italic("fa-solid fa-italic", "fa-solid fa-italic"),
    link("fa-solid fa-link", "fa-solid fa-link"),
    inserthr("fa-solid fa-minus", "fa-solid fa-minus"),
    imenu("fa-solid fa-bars", "fa-solid fa-bars"),
    minus("fa-solid fa-minus", "fa-solid fa-minus"),
    checked("fa-solid fa-check", "fa-solid fa-check"),
    mobile("fa-solid fa-mobile-alt", "fa-solid fa-mobile-alt"),
    mouse("fa-solid fa-mouse-pointer", "fa-solid fa-mouse-pointer"),
    outdent("fa-solid fa-outdent", "fa-solid fa-outdent"),
    picture("fa-solid fa-image", "fa-solid fa-image"),
    print("fa-solid fa-print", "fa-solid fa-print"),
    numbers("fa-solid fa-list-ol", "fa-solid fa-list-ol"),
    right("fa-solid fa-arrow-right", "fa-solid fa-arrow-right"),
    search("fa-solid fa-search", "fa-solid fa-search"),
    question("fa-solid fa-question", "fa-solid fa-question"),
    remove("fa-solid fa-times", "fa-solid fa-times"),
    sort("fa-solid fa-sort", "fa-solid fa-sort"),
    ichecked("fa-solid fa-check", "fa-solid fa-check"),
    strikethrough("fa-solid fa-strikethrough", "fa-solid fa-strikethrough"),
    sub("fa-solid fa-subscript", "fa-solid fa-subscript"),
    iconsuper("fa-solid fa-superscript", "fa-solid fa-superscript"),
    transparent("fa-solid fa-fill", "fa-solid fa-fill"),
    idown("fa-solid fa-chevron-down", "fa-solid fa-chevron-down"),
    left("fa-solid fa-chevron-left", "fa-solid fa-chevron-left"),
    iright("fa-solid fa-chevron-right", "fa-solid fa-chevron-right"),
    iup("fa-solid fa-chevron-up", "fa-solid fa-chevron-up"),
    undo("fa-solid fa-undo", "fa-solid fa-undo"),
    redo("fa-solid fa-redo", "fa-solid fa-redo"),
    upload("fa-solid fa-upload", "fa-solid fa-upload"),
    zoomin("fa-solid fa-search-plus", "fa-solid fa-search-plus"),
    zoomout("fa-solid fa-search-minus", "fa-solid fa-search-minus"),
    underline("fa-solid fa-underline", "fa-solid fa-underline"),
    ierror("fa-solid fa-exclamation-circle", "fa-solid fa-exclamation-circle"),
    refresh("fa-solid fa-sync-alt", "fa-solid fa-sync-alt"),
    arrowdrop("fa-solid fa-chevron-down", "fa-solid fa-chevron-down"),
    check("fa-solid fa-check", "fa-solid fa-check"),
    cichecked("fa-solid fa-check", "fa-solid fa-check"),
    add("fa-solid fa-plus", "fa-solid fa-plus"),
    iclose("fa-solid fa-times", "fa-solid fa-times"),
    cmdbox("fa-solid fa-th", "fa-solid fa-th"),
    cdate("fa-solid fa-calendar", "fa-solid fa-calendar"),
    color("fa-solid fa-palette", "fa-solid fa-palette"),
    cdelete("fa-solid fa-trash-alt", "fa-solid fa-trash-alt"),
    dotted("fa-solid fa-ellipsis-h", "fa-solid fa-ellipsis-h"),
    cdatetime("fa-solid fa-calendar-alt", "fa-solid fa-calendar-alt"),
    helpinput("fa-solid fa-question-circle", "fa-solid fa-question-circle"),
    getter("fa-solid fa-list", "fa-solid fa-list"),
    cfile("fa-solid fa-file", "fa-solid fa-file"),
    info("fa-solid fa-info-circle", "fa-solid fa-info-circle"),
    land("fa-solid fa-expand-arrows-alt", "fa-solid fa-expand-arrows-alt"),
    max("fa-solid fa-expand-alt", "fa-solid fa-expand-alt"),
    min("fa-solid fa-compress-alt", "fa-solid fa-compress-alt"),
    location("fa-solid fa-map-marker-alt", "fa-solid fa-map-marker-alt"),
    opt("fa-solid fa-cog", "fa-solid fa-cog"),
    pop("fa-solid fa-pop-out", "fa-solid fa-pop-out"),
    pin("fa-solid fa-thumbtack", "fa-solid fa-thumbtack"),
    radio("fa-solid fa-dot-circle", "fa-solid fa-dot-circle"),
    radiochecked("fa-solid fa-dot-circle", "fa-solid fa-dot-circle"),
    popbox("fa-solid fa-window-restore", "fa-solid fa-window-restore"),
    crefresh("fa-solid fa-sync-alt", "fa-solid fa-sync-alt"),
    restore("fa-solid fa-window-restore", "fa-solid fa-window-restore"),
    cremove("fa-solid fa-times", "fa-solid fa-times"),
    time("fa-solid fa-clock", "fa-solid fa-clock"),
    cselect("fa-solid fa-check-square", "fa-solid fa-check-square"),
    csave("fa-solid fa-save", "fa-solid fa-save"),
    toggle("fa-solid fa-toggle-off", "fa-solid fa-toggle-off"),
    togglechecked("fa-solid fa-toggle-on", "fa-solid fa-toggle-on"),
    alingleft("fa-solid fa-align-left", "fa-solid fa-align-left"),
    aligncenter("fa-solid fa-align-center", "fa-solid fa-align-center"),
    alignjustify("fa-solid fa-align-justify", "fa-solid fa-align-justify"),
    alignright("fa-solid fa-align-right", "fa-solid fa-align-right"),
    singleleft("fa-solid fa-chevron-left", "fa-solid fa-chevron-left"),
    singleright("fa-solid fa-chevron-right", "fa-solid fa-chevron-right"),
    singleup("fa-solid fa-chevron-up", "fa-solid fa-chevron-up"),
    singledown("fa-solid fa-chevron-down", "fa-solid fa-chevron-down"),
    smalldown("fa-solid fa-chevron-down", "fa-solid fa-chevron-down"),
    smallup("fa-solid fa-chevron-up", "fa-solid fa-chevron-up"),
    arrowleft("fa-solid fa-arrow-left", "fa-solid fa-arrow-left"),
    arrowright("fa-solid fa-arrow-right", "fa-solid fa-arrow-right"),
    carrowtop("fa-solid fa-arrow-up", "fa-solid fa-arrow-up"),
    arrowbottom("fa-solid fa-arrow-down", "fa-solid fa-arrow-down"),
    circleleft("fa-solid fa-arrow-circle-left", "fa-solid fa-arrow-circle-left"),
    circleright("fa-solid fa-arrow-circle-right", "fa-solid fa-arrow-circle-right"),
    circleup("fa-solid fa-arrow-circle-up", "fa-solid fa-arrow-circle-up"),
    circledown("fa-solid fa-arrow-circle-down", "fa-solid fa-arrow-circle-down"),
    doubleleft("fa-solid fa-angle-double-left", "fa-solid fa-angle-double-left"),
    doubleright("fa-solid fa-angle-double-right", "fa-solid fa-angle-double-right"),
    doubleup("fa-solid fa-angle-double-up", "fa-solid fa-angle-double-up"),
    doubledown("fa-solid fa-angle-double-down", "fa-solid fa-angle-double-down"),
    first("fa-solid fa-step-backward", "fa-solid fa-step-backward"),
    prev("fa-solid fa-backward", "fa-solid fa-backward"),
    next("fa-solid fa-forward", "fa-solid fa-forward"),
    last("fa-solid fa-step-forward", "fa-solid fa-step-forward"),
    number("fa-solid fa-hashtag", "fa-solid fa-hashtag"),
    
    // 数字图标
    number0("fa-solid fa-zero", "fa-solid fa-zero"),
    number1("fa-solid fa-one", "fa-solid fa-one"),
    number2("fa-solid fa-two", "fa-solid fa-two"),
    number3("fa-solid fa-three", "fa-solid fa-three"),
    number4("fa-solid fa-four", "fa-solid fa-four"),
    number5("fa-solid fa-five", "fa-solid fa-five"),
    number6("fa-solid fa-six", "fa-solid fa-six"),
    number7("fa-solid fa-seven", "fa-solid fa-seven"),
    number8("fa-solid fa-eight", "fa-solid fa-eight"),
    number9("fa-solid fa-nine", "fa-solid fa-nine");

    private String type;
    private String name;
    private String value;
    private String imageClass;


    CustomImageType(String imageClass, String value) {
        this.type = name();
        this.name = imageClass;
        this.value = value;
        this.imageClass = imageClass;
    }

    @Override
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Override
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public String getImageClass() {
        return imageClass;
    }

    public void setImageClass(String imageClass) {
        this.imageClass = imageClass;
    }
}
