package net.ooder.esd.annotation.ui;


import net.ooder.annotation.IconEnumstype;

// 保留前三个已经正确升级的图标
public enum CustomImageType implements IconEnumstype {
    o("fas fa-lg fa-calendar-plus", "fas fa-lg fa-calendar-plus"),
    close("fas fa-lg fa-times", "fas fa-lg fa-times"),
    notch("fas fa-lg fa-circle-notch", "fas fa-lg fa-circle-notch"),
    
    // spafont 图标升级
    data("fas fa-database", "fas fa-database"),
    debug("fas fa-bug", "fas fa-bug"),
    debug1("fas fa-vial", "fas fa-vial"),
    video("fas fa-video", "fas fa-video"),
    webapi("fas fa-server", "fas fa-server"),
    cut("fas fa-cut", "fas fa-cut"),
    delete("fas fa-trash-alt", "fas fa-trash-alt"),
    designview("fas fa-paint-brush", "fas fa-paint-brush"),
    icondomnode("fas fa-code-branch", "fas fa-code-branch"),
    deletepath("fas fa-unlink", "fas fa-unlink"),
    edit("fas fa-edit", "fas fa-edit"),
    deletefile("fas fa-file-excel", "fas fa-file-excel"),
    event("fas fa-bolt", "fas fa-bolt"),
    editpath("fas fa-link", "fas fa-link"),
    empty("fas fa-archive", "fas fa-archive"),
    file("fas fa-file", "fas fa-file"),
    explore("fas fa-search", "fas fa-search"),
    fillcell("fas fa-fill", "fas fa-fill"),
    filexml("fas fa-file-code", "fas fa-file-code"),
    formatjs("fas fa-file-js", "fas fa-file-js"),
    formatjson("fas fa-file-export", "fas fa-file-export"),
    frame("fas fa-border-all", "fas fa-border-all"),
    hmirror("fas fa-arrows-h", "fas fa-arrows-h"),
    hash("fas fa-hashtag", "fas fa-hashtag"),
    function("fas fa-cogs", "fas fa-cogs"),
    gallery("fas fa-images", "fas fa-images"),
    html("fas fa-code", "fas fa-code"),
    arrowtop("fas fa-arrow-up", "fas fa-arrow-up"),
    bigup("fas fa-arrow-circle-up", "fas fa-arrow-circle-up"),
    indent("fas fa-indent", "fas fa-indent"),
    js("fab fa-js", "fab fa-js"),
    jumpto("fas fa-jump-forward", "fas fa-jump-forward"),
    language("fas fa-language", "fas fa-language"),
    sfile("fas fa-file-code", "fas fa-file-code"),
    manual("fas fa-book", "fas fa-book"),
    links("fas fa-link", "fas fa-link"),
    login("fas fa-sign-in-alt", "fas fa-sign-in-alt"),
    movebackward("fas fa-backward", "fas fa-backward"),
    module("fas fa-cube", "fas fa-cube"),
    down("fas fa-chevron-down", "fas fa-chevron-down"),
    moveforward("fas fa-forward", "fas fa-forward"),
    up("fas fa-chevron-up", "fas fa-chevron-up"),
    newfile("fas fa-file-export", "fas fa-file-export"),
    newprj("fas fa-project-diagram", "fas fa-project-diagram"),
    ok("fas fa-check", "fas fa-check"),
    openprj("fas fa-folder-open", "fas fa-folder-open"),
    iconpackage("fas fa-box", "fas fa-box"),
    options("fas fa-cog", "fas fa-cog"),
    page("fas fa-file-alt", "fas fa-file-alt"),
    phonegap("fas fa-mobile-alt", "fas fa-mobile-alt"),
    paste("fas fa-paste", "fas fa-paste"),
    pic("fas fa-image", "fas fa-image"),
    previewpage("fas fa-eye", "fas fa-eye"),
    preview("fas fa-eye", "fas fa-eye"),
    property("fas fa-sliders-h", "fas fa-sliders-h"),
    rename("fas fa-edit", "fas fa-edit"),
    project("fas fa-project-diagram", "fas fa-project-diagram"),
    rendermode("fas fa-palette", "fas fa-palette"),
    resetpath("fas fa-sync-alt", "fas fa-sync-alt"),
    rotateleft("fas fa-undo", "fas fa-undo"),
    rotateright("fas fa-redo", "fas fa-redo"),
    rpc("fas fa-network-wired", "fas fa-network-wired"),
    save("fas fa-save", "fas fa-save"),
    saveall("fas fa-save", "fas fa-save"),
    searchreplace("fas fa-search", "fas fa-search"),
    select("fas fa-check-square", "fas fa-check-square"),
    select1("fas fa-check-square", "fas fa-check-square"),
    setup("fas fa-cog", "fas fa-cog"),
    shouhou("fas fa-headset", "fas fa-headset"),
    star("fas fa-star", "fas fa-star"),
    settingprj("fas fa-cog", "fas fa-cog"),
    theme("fas fa-palette", "fas fa-palette"),
    tool("fas fa-toolbox", "fas fa-toolbox"),
    unkown("fas fa-question", "fas fa-question"),
    tools("fas fa-tools", "fas fa-tools"),
    values("fas fa-list-ol", "fas fa-list-ol"),
    ivideo("fas fa-video", "fas fa-video"),
    var("fas fa-code", "fas fa-code"),
    vmirror("fas fa-arrows-v", "fas fa-arrows-v"),
    shukongjian("fas fa-cubes", "fas fa-cubes"),
    viewpoint("fas fa-eye", "fas fa-eye"),
    action("fas fa-play", "fas fa-play"),
    x("fas fa-times", "fas fa-times"),
    wbdiconsoftswf("fab fa-adobe", "fab fa-adobe"),
    action1("fas fa-play-circle", "fas fa-play-circle"),
    addpath("fas fa-plus-square", "fas fa-plus-square"),
    alignh("fas fa-align-center", "fas fa-align-center"),
    alignl("fas fa-align-left", "fas fa-align-left"),
    alignc("fas fa-align-center", "fas fa-align-center"),
    alignm("fas fa-align-justify", "fas fa-align-justify"),
    aligncell("fas fa-table", "fas fa-table"),
    alignt("fas fa-align-top", "fas fa-align-top"),
    alignwh("fas fa-expand-arrows-alt", "fas fa-expand-arrows-alt"),
    alingb("fas fa-align-bottom", "fas fa-align-bottom"),
    alignw("fas fa-expand-alt", "fas fa-expand-alt"),
    array("fas fa-list", "fas fa-list"),
    app("fas fa-mobile-alt", "fas fa-mobile-alt"),
    arrow("fas fa-arrow-right", "fas fa-arrow-right"),
    audio("fas fa-volume-up", "fas fa-volume-up"),
    breakpath("fas fa-unlink", "fas fa-unlink"),
    astext("fas fa-font", "fas fa-font"),
    cancel("fas fa-times", "fas fa-times"),
    saudio("fas fa-volume-up", "fas fa-volume-up"),
    buttonviews("fas fa-th", "fas fa-th"),
    button("fas fa-square", "fas fa-square"),
    block("fas fa-cube", "fas fa-cube"),
    buttonview("fas fa-th-large", "fas fa-th-large"),
    checkbox("fas fa-check-square", "fas fa-check-square"),
    iconslist("fas fa-list", "fas fa-list"),
    hiddeninput("fas fa-key", "fas fa-key"),
    imagebutton("fas fa-image", "fas fa-image"),
    image("fas fa-image", "fas fa-image"),
    label("fas fa-font", "fas fa-font"),
    layout("fas fa-th", "fas fa-th"),
    input("fas fa-keyboard", "fas fa-keyboard"),
    clear("fas fa-times-circle", "fas fa-times-circle"),
    iconclass("fas fa-code", "fas fa-code"),
    click("fas fa-mouse-pointer", "fas fa-mouse-pointer"),
    list("fas fa-list", "fas fa-list"),
    closepath("fas fa-times-circle", "fas fa-times-circle"),
    clone("fas fa-clone", "fas fa-clone"),
    menu("fas fa-bars", "fas fa-bars"),
    menubar("fas fa-ellipsis-h", "fas fa-ellipsis-h"),
    nativebutton("fas fa-square", "fas fa-square"),
    codeview("fas fa-code", "fas fa-code"),
    code("fas fa-code", "fas fa-code"),
    numberinput("fas fa-hashtag", "fas fa-hashtag"),
    coin("fas fa-coins", "fas fa-coins"),
    com("fas fa-plug", "fas fa-plug"),
    conf("fas fa-cog", "fas fa-cog"),
    conf1("fas fa-cogs", "fas fa-cogs"),
    coms("fas fa-plug", "fas fa-plug"),
    console("fas fa-terminal", "fas fa-terminal"),
    config("fas fa-cog", "fas fa-cog"),
    pager("fas fa-sync-alt", "fas fa-sync-alt"),
    panel("fas fa-layer-group", "fas fa-layer-group"),
    copy("fas fa-copy", "fas fa-copy"),
    progressbar("fas fa-tasks", "fas fa-tasks"),
    richeditor("fas fa-edit", "fas fa-edit"),
    radiobox("fas fa-dot-circle", "fas fa-dot-circle"),
    slider("fas fa-sliders-h", "fas fa-sliders-h"),
    password("fas fa-lock", "fas fa-lock"),
    span("fas fa-font", "fas fa-font"),
    stacks("fas fa-layer-group", "fas fa-layer-group"),
    css("fab fa-css3-alt", "fab fa-css3-alt"),
    statusbtns("fas fa-tasks", "fas fa-tasks"),
    spinner("fas fa-spinner", "fas fa-spinner"),
    tabs("fas fa-table", "fas fa-table"),
    statusbutton("fas fa-toggle-on", "fas fa-toggle-on"),
    textarea("fas fa-align-left", "fas fa-align-left"),
    timeinput("fas fa-clock", "fas fa-clock"),
    toolbar("fas fa-toolbar", "fas fa-toolbar"),
    timer("fas fa-stopwatch", "fas fa-stopwatch"),
    treebar("fas fa-sitemap", "fas fa-sitemap"),
    treeview("fas fa-tree", "fas fa-tree"),
    url("fas fa-link", "fas fa-link"),
    custom("fas fa-wrench", "fas fa-wrench"),
    com2("fas fa-plug", "fas fa-plug"),
    com3("fas fa-plug", "fas fa-plug"),
    mqtt("fas fa-network-wired", "fas fa-network-wired"),
    
    // ood 图标升级
    ood("fas fa-cube", "fas fa-cube"),
    placeholder("fas fa-map-marker-alt", "fas fa-map-marker-alt"),
    iempty("fas fa-box-open", "fas fa-box-open"),
    loading("fas fa-spinner", "fas fa-spinner"),
    istar("fas fa-star", "fas fa-star"),
    smill("fas fa-smile", "fas fa-smile"),
    trash("fas fa-trash", "fas fa-trash"),
    error("fas fa-exclamation-triangle", "fas fa-exclamation-triangle"),
    back("fas fa-arrow-left", "fas fa-arrow-left"),
    bold("fas fa-bold", "fas fa-bold"),
    bgcolor("fas fa-fill", "fas fa-fill"),
    breaklink("fas fa-unlink", "fas fa-unlink"),
    clock("fas fa-clock", "fas fa-clock"),
    circle("fas fa-circle", "fas fa-circle"),
    ibigup("fas fa-arrow-up", "fas fa-arrow-up"),
    icode("fas fa-code", "fas fa-code"),
    idialog("fas fa-window-maximize", "fas fa-window-maximize"),
    bullet("fas fa-circle", "fas fa-circle"),
    date("fas fa-calendar", "fas fa-calendar"),
    dragadd("fas fa-plus", "fas fa-plus"),
    dragmove("fas fa-arrows-alt", "fas fa-arrows-alt"),
    dragcopy("fas fa-copy", "fas fa-copy"),
    dropdown("fas fa-chevron-down", "fas fa-chevron-down"),
    dragstop("fas fa-stop", "fas fa-stop"),
    ifile("fas fa-file", "fas fa-file"),
    expand("fas fa-chevron-down", "fas fa-chevron-down"),
    fold("fas fa-chevron-right", "fas fa-chevron-right"),
    filter("fas fa-filter", "fas fa-filter"),
    font("fas fa-font", "fas fa-font"),
    forecolor("fas fa-palette", "fas fa-palette"),
    formatbrush("fas fa-paint-brush", "fas fa-paint-brush"),
    formatclear("fas fa-eraser", "fas fa-eraser"),
    iindent("fas fa-indent", "fas fa-indent"),
    ihtml("fas fa-code", "fas fa-code"),
    italic("fas fa-italic", "fas fa-italic"),
    link("fas fa-link", "fas fa-link"),
    inserthr("fas fa-minus", "fas fa-minus"),
    imenu("fas fa-bars", "fas fa-bars"),
    minus("fas fa-minus", "fas fa-minus"),
    checked("fas fa-check", "fas fa-check"),
    mobile("fas fa-mobile-alt", "fas fa-mobile-alt"),
    mouse("fas fa-mouse-pointer", "fas fa-mouse-pointer"),
    outdent("fas fa-outdent", "fas fa-outdent"),
    picture("fas fa-image", "fas fa-image"),
    print("fas fa-print", "fas fa-print"),
    numbers("fas fa-list-ol", "fas fa-list-ol"),
    right("fas fa-arrow-right", "fas fa-arrow-right"),
    search("fas fa-search", "fas fa-search"),
    question("fas fa-question", "fas fa-question"),
    remove("fas fa-times", "fas fa-times"),
    sort("fas fa-sort", "fas fa-sort"),
    ichecked("fas fa-check", "fas fa-check"),
    strikethrough("fas fa-strikethrough", "fas fa-strikethrough"),
    sub("fas fa-subscript", "fas fa-subscript"),
    iconsuper("fas fa-superscript", "fas fa-superscript"),
    transparent("fas fa-fill", "fas fa-fill"),
    idown("fas fa-chevron-down", "fas fa-chevron-down"),
    left("fas fa-chevron-left", "fas fa-chevron-left"),
    iright("fas fa-chevron-right", "fas fa-chevron-right"),
    iup("fas fa-chevron-up", "fas fa-chevron-up"),
    undo("fas fa-undo", "fas fa-undo"),
    redo("fas fa-redo", "fas fa-redo"),
    upload("fas fa-upload", "fas fa-upload"),
    zoomin("fas fa-search-plus", "fas fa-search-plus"),
    zoomout("fas fa-search-minus", "fas fa-search-minus"),
    underline("fas fa-underline", "fas fa-underline"),
    ierror("fas fa-exclamation-circle", "fas fa-exclamation-circle"),
    refresh("fas fa-sync-alt", "fas fa-sync-alt"),
    arrowdrop("fas fa-chevron-down", "fas fa-chevron-down"),
    check("fas fa-check", "fas fa-check"),
    cichecked("fas fa-check", "fas fa-check"),
    add("fas fa-plus", "fas fa-plus"),
    iclose("fas fa-times", "fas fa-times"),
    cmdbox("fas fa-th", "fas fa-th"),
    cdate("fas fa-calendar", "fas fa-calendar"),
    color("fas fa-palette", "fas fa-palette"),
    cdelete("fas fa-trash-alt", "fas fa-trash-alt"),
    dotted("fas fa-ellipsis-h", "fas fa-ellipsis-h"),
    cdatetime("fas fa-calendar-alt", "fas fa-calendar-alt"),
    helpinput("fas fa-question-circle", "fas fa-question-circle"),
    getter("fas fa-list", "fas fa-list"),
    cfile("fas fa-file", "fas fa-file"),
    info("fas fa-info-circle", "fas fa-info-circle"),
    land("fas fa-expand-arrows-alt", "fas fa-expand-arrows-alt"),
    max("fas fa-expand-alt", "fas fa-expand-alt"),
    min("fas fa-compress-alt", "fas fa-compress-alt"),
    location("fas fa-map-marker-alt", "fas fa-map-marker-alt"),
    opt("fas fa-cog", "fas fa-cog"),
    pop("fas fa-pop-out", "fas fa-pop-out"),
    pin("fas fa-thumbtack", "fas fa-thumbtack"),
    radio("fas fa-dot-circle", "fas fa-dot-circle"),
    radiochecked("fas fa-dot-circle", "fas fa-dot-circle"),
    popbox("fas fa-window-restore", "fas fa-window-restore"),
    crefresh("fas fa-sync-alt", "fas fa-sync-alt"),
    restore("fas fa-window-restore", "fas fa-window-restore"),
    cremove("fas fa-times", "fas fa-times"),
    time("fas fa-clock", "fas fa-clock"),
    cselect("fas fa-check-square", "fas fa-check-square"),
    csave("fas fa-save", "fas fa-save"),
    toggle("fas fa-toggle-off", "fas fa-toggle-off"),
    togglechecked("fas fa-toggle-on", "fas fa-toggle-on"),
    alingleft("fas fa-align-left", "fas fa-align-left"),
    aligncenter("fas fa-align-center", "fas fa-align-center"),
    alignjustify("fas fa-align-justify", "fas fa-align-justify"),
    alignright("fas fa-align-right", "fas fa-align-right"),
    singleleft("fas fa-chevron-left", "fas fa-chevron-left"),
    singleright("fas fa-chevron-right", "fas fa-chevron-right"),
    singleup("fas fa-chevron-up", "fas fa-chevron-up"),
    singledown("fas fa-chevron-down", "fas fa-chevron-down"),
    smalldown("fas fa-chevron-down", "fas fa-chevron-down"),
    smallup("fas fa-chevron-up", "fas fa-chevron-up"),
    arrowleft("fas fa-arrow-left", "fas fa-arrow-left"),
    arrowright("fas fa-arrow-right", "fas fa-arrow-right"),
    carrowtop("fas fa-arrow-up", "fas fa-arrow-up"),
    arrowbottom("fas fa-arrow-down", "fas fa-arrow-down"),
    circleleft("fas fa-arrow-circle-left", "fas fa-arrow-circle-left"),
    circleright("fas fa-arrow-circle-right", "fas fa-arrow-circle-right"),
    circleup("fas fa-arrow-circle-up", "fas fa-arrow-circle-up"),
    circledown("fas fa-arrow-circle-down", "fas fa-arrow-circle-down"),
    doubleleft("fas fa-angle-double-left", "fas fa-angle-double-left"),
    doubleright("fas fa-angle-double-right", "fas fa-angle-double-right"),
    doubleup("fas fa-angle-double-up", "fas fa-angle-double-up"),
    doubledown("fas fa-angle-double-down", "fas fa-angle-double-down"),
    first("fas fa-step-backward", "fas fa-step-backward"),
    prev("fas fa-backward", "fas fa-backward"),
    next("fas fa-forward", "fas fa-forward"),
    last("fas fa-step-forward", "fas fa-step-forward"),
    number("fas fa-hashtag", "fas fa-hashtag"),
    
    // 数字图标
    number0("fas fa-zero", "fas fa-zero"),
    number1("fas fa-one", "fas fa-one"),
    number2("fas fa-two", "fas fa-two"),
    number3("fas fa-three", "fas fa-three"),
    number4("fas fa-four", "fas fa-four"),
    number5("fas fa-five", "fas fa-five"),
    number6("fas fa-six", "fas fa-six"),
    number7("fas fa-seven", "fas fa-seven"),
    number8("fas fa-eight", "fas fa-eight"),
    number9("fas fa-nine", "fas fa-nine");

    private String type;
    private String name;
    private String value;
    private String imageClass;


    CustomImageType(String imageClass, String value) {
        this.type = name();
        this.name = imageClass;
        this.value = value;
        this.imageClass = imageClass;
    }

    @Override
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Override
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public String getImageClass() {
        return imageClass;
    }

    public void setImageClass(String imageClass) {
        this.imageClass = imageClass;
    }
}
